CREATE TABLE IF NOT EXISTS users (
			id INT AUTO_INCREMENT PRIMARY KEY,
			user_id VARCHAR(100) NOT NULL UNIQUE,
			phone_number VARCHAR(20) NOT NULL UNIQUE,
			pin VARCHAR(255) NOT NULL,
			first_name VARCHAR(100) NOT NULL,
            last_name VARCHAR(100) NOT NULL,
			address VARCHAR(100) NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
		) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wallets (
			id INT AUTO_INCREMENT PRIMARY KEY,
			user_id VARCHAR(100) NOT NULL,
			balance DECIMAL(15,2) DEFAULT 0.00,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
		) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS transactions (
			id INT AUTO_INCREMENT PRIMARY KEY,
			transaction_id VARCHAR(100) NOT NULL,
			user_id VARCHAR(100) NOT NULL,
			type VARCHAR(20) NOT NULL,
			amount DECIMAL(15,2) NOT NULL,
            balance_before DECIMAL(15,2) DEFAULT NULL,
            balance_after DECIMAL(15,2) DEFAULT NULL,
			description TEXT,
			status VARCHAR(20) NOT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
		) ENGINE=InnoDB;